### ISSUE TITLE
GKE + PersistentVolumes

### ISSUE THREAD

**Issue by andresrivero** [sredevopsorg/ghost-on-kubernetes#67]
I found that running this as is on GKE required the use of an initContainer to force the content folder to be nonroot. I believe GKE has some security context or preference that PVCs mounted in this manner are overwritten as root. Even setting it as readOnly: false would not change it. 

This is what I added to my GKE deployment yaml, otherwise Ghost is unable to mkdir the content/settings directory on first run and is unable to edit items within the content/ folder.

template:
    metadata:
      namespace: ghostk3slocal
      labels:
        app: ghostk3s
    spec:
      volumes:
        - name: ghostk3s-static-ghost
          persistentVolumeClaim:
            claimName: ghostk3s-static-ghost
        - name: ghost-config-prod
          secret:
            secretName: ghost-config-prod
            defaultMode: 420
        - name: tmp
          emptyDir:
            sizeLimit: 128Mi
      _initContainers:
      - name: chmod-er
        image: busybox:latest
        command:
        - /bin/chown
        - -R
        - "1000:1000"  
        - /var/lib/ghost/content
        volumeMounts:
        - name: ghostk3s-static-ghost  # or whatever
          mountPath: /var/lib/ghost/content_
      containers:
        - name: ghostk3s

**Comment by ngeorger** [comment]
> I found that running this as is on GKE required the use of an initContainer to force the content folder to be nonroot. I believe GKE has some security context or preference that PVCs mounted in this manner are overwritten as root. Even setting it as readOnly: false would not change it.
> 
> This is what I added to my GKE deployment yaml, otherwise Ghost is unable to mkdir the content/settings directory on first run and is unable to edit items within the content/ folder.
> 
> template: metadata: namespace: ghostk3slocal labels: app: ghostk3s spec: volumes: - name: ghostk3s-static-ghost persistentVolumeClaim: claimName: ghostk3s-static-ghost - name: ghost-config-prod secret: secretName: ghost-config-prod defaultMode: 420 - name: tmp emptyDir: sizeLimit: 128Mi _initContainers: - name: chmod-er image: busybox:latest command: - /bin/chown - -R - "1000:1000" - /var/lib/ghost/content volumeMounts: - name: ghostk3s-static-ghost # or whatever mountPath: /var/lib/ghost/content_ containers: - name: ghostk3s

I'm gonna review and fix it as soon as possible, thank you very much for your report :)

**Comment by andresrivero** [comment]
I can look into it soon - I know this is a little hacky.

**Comment by ngeorger** [comment]
Fixed!
